### ISSUE TITLE
Adding SIF interaction types

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1022]
## Description of new feature

Make available for the user, additional SIF interaction types. 

- [x] controls-phosphorylation-of
- [x] controls-expression-of
- [x] in-complex-with
- [x] interacts-with
- [ ] controls-state-change-of
- [ ] controls-transport-of
- [ ] catalysis-precedes

 NB: Do not implement `neighbor-of`

## Motivation for new feature

Allow the user access to additional interaction types that they may be interested in.

Notes:

See http://www.pathwaycommons.org/pc2/formats for SIF types
Also need to think about user-friendly labels, grouping

**Comment by jvwong** [comment]
Human readable version and grouping:

- Phosphorylation etc
- Expression
- Binding
- Complex
- Other

**Comment by jvwong** [comment]
Updated:

- Phosphorylation etc
  - [controls-phosphorylation-of, controls-state-change-of]
- Expression
  - controls-expression-of
- Binding
  - interacts-with
- Other
  - [controls-transport-of, catalysis-precedes]

**Comment by maxkfranz** [comment]
Notes:

- Complex needs to be handled differently, w.r.t. :
  - Filtering : It dominates the filtering metric, because the BioPAX to SIF conversion rule for a complex creates K<sub>N</sub>.
  - Display : It visually pollutes the graph.
- Options
  - (1) Keep complexes in the results as they are now, but toggle the complex group checkbox off by default.  Helps with initial display, but doesn't help with filtering.
  - (2) Mark nodes that participate in complexes in the UI and put the data for the edges of type complex in the node for tooltip display.  All edges of type complex are omitted from the filtering rules and from display.
  - (3) Don't include complexes at all.

Do (3) for the initial release, and explore other options for future releases.

**Comment by jvwong** [comment]
I think we need to update  [/src/server/graph-generation/interaction/index.js](https://github.com/PathwayCommons/app-ui/blob/06214039999468e0f4da0bcd269276a551b51448/src/server/graph-generation/interaction/index.js) to fetch different `patterns` from PC/graph including: 'controls-state-change-of', 'controls-transport-of', 'catalysis-precedes'. Exclude 'in-complex-with'.

**Comment by d2fong** [comment]
I guess I misunderstood how the service works.  I thought all the interactions were in a single file regardless of response params.

**Comment by jvwong** [comment]
yeah I think you can filter. However, in my PR, the PC calls take much longer with 'state-change-of'...

**Comment by jvwong** [comment]
ALso now you can see those other interaction types in the UI (other)
