### ISSUE TITLE
Degree metric biased towards certain interaction types

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1055]
One of the trade-offs of ordering on degree: 'in-complex-with' interactions (often > 1 hops away from the query node)  tend to get included in the display at the expense of other interactions types. This, like 'neighbor-of' is perhaps a bit of an artifact of SIF? Anyways, it would be nice to see more of the other types (expression, phosphorylation) rather than hairballs.

Some examples, with 'in-complex-with' included (left) and excluded (right):

[FGF9](http://appsbeta.pathwaycommons.org/interactions?source=FGF9)   
![fgf9_incomplexwithonoff](https://user-images.githubusercontent.com/4706307/44666177-d4f17900-a9e5-11e8-9a29-f8c8c0ee63c9.png)

[CDKN1A](http://appsbeta.pathwaycommons.org/interactions?source=CDKN1A)   
![cdkn1a_incomplexwithonoff](https://user-images.githubusercontent.com/4706307/44666184-d7ec6980-a9e5-11e8-9389-27bc9f32334c.png)

[IL6](http://appsbeta.pathwaycommons.org/interactions?source=IL6)   

![il6_incomplexwithonoff](https://user-images.githubusercontent.com/4706307/44666193-dc188700-a9e5-11e8-8088-0301c909713e.png)

**Comment by maxkfranz** [comment]
Complex isn't a great fit for SIF, because it creates subgraphs of size N that are [K<sub>N</sub>](https://en.wikipedia.org/wiki/Complete_graph).  Edges aren't a good way to visualise that data.  They're noisy.  It's hard to distinguish which nodes belong to which complex sets, for example.

It would be better to use compound nodes, layouts, or node colours to visualise complex membership.
