### ISSUE TITLE
Where's my hairball?

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#1078]
If we use the new sifgraph service, the results look something like this:
@maxkfranz @jvwong @IgorRodchenkov 
![screen shot 2018-09-18 at 11 59 26 am](https://user-images.githubusercontent.com/2328291/45700363-51d1c780-bb3a-11e8-834f-9bdbbc3b45af.png)

Does it still make sense to only show 25 nodes?

@IgorRodchenkov Do all results from this new service exhibit these properties (all nodes connected to the source, no edges between non-source nodes?

**Comment by IgorRodchenkov** [comment]
Indeed, Sifgraph service returns only those edges where a source/target node is present, e.g.: 

`http://www.pathwaycommons.org/sifgraph/v1/neighborhood?direction=UNDIRECTED&pattern=CONTROLS_EXPRESSION_OF&source=TP53`

I think, this is a feature of the [Sifgraph java library](https://github.com/PathwayCommons/sifgraph), but unsure whether it is expected behavior or side-effect, though.

Ozgun @ozgunbabur , what do you think?

**Comment by ozgunbabur** [comment]
For the neighborhood queries, the new SIF service should be returning a star graph instead of a hairball. This is because the query runs on the big SIF graph itself, and not on the big BioPAX graph as previously done. But I don't know why there are few targets of TP53 in the results. There are 799 targets of TP53 with this SIF type in PC9.

**Comment by jvwong** [comment]
> But I don't know why there are few targets of TP53 in the results. There are 799 targets of TP53 with this SIF type in PC9.

@ozgunbabur - the app ranks nodes by degree then sets a ceiling on the number of nodes (right now max = 25).

Another issue then using the SifGraph backend is the node ranking algorithm: If the service just returns those connected to the query, then the rank metric becomes pointless - every node but the query gets rank 1. In this case we're just showing the nodes in the order they appear in the service response.

**Comment by d2fong** [comment]
In this case wouldn't it prioritize nodes that have more than one edge type to the source?  I think it just means that nodes with more than one edge to the source will get prioritized over nodes with only one edge to the source.

**Comment by jvwong** [comment]
Argh - bug in my code that overwrites the degree calculation.
