### ISSUE TITLE
Tests: Remove live API calls to third parties (Enrichment, Summary)

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1125]
Certain services fetch from third-party instances, but we should instead be testing the local  processing assuming a successful call.

This applies to both /enrichment and /summary code.

I'll leave the pc/interaction test calls and update mocha to obtain a global fetch instance.

**Comment by maxkfranz** [comment]
Approaches:

(1) Create a mock `fetch()` function that just loads a predetermined file per test.  Since we're using `global.fetch()` on the server this should be straightforward.

(2) Refactor, where necessary, the services into separate raw fetch functions and processing functions.  Only run the processing functions in the tests.

**Comment by jvwong** [comment]
I'm going to do (2) for enrichment services.
