### ISSUE TITLE
Validation: Sort query before caching

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#1144]
The goal is to cache validation queries in a more efficient manner. As a first step, sort the query token array alphabetically before it hits the cache. Currently, something like ['TP53', 'MDM2'] is not the same as ['MDM2', 'TP53'].

**Comment by maxkfranz** [comment]
options.sort: true in node-object-hash

https://www.npmjs.com/package/node-object-hash#constructor-requirenode-object-hashoptions

**Comment by jvwong** [comment]
The docs seem to say options.sort = true by default?

>Parameters:
> options:object - object with hasher config options
options.coerce:boolean - if true performs type coercion (default: true); e.g. hash(true) == hash('1') == hash(1), hash(false) == hash('0') == hash(0)
options.sort:boolean - if true performs sorting on objects, arrays, etc. (default: true);
options.alg:string - sets default hash algorithm (default: 'sha256'); can be overridden in hash method;
options.enc:string - sets default hash encoding (default: 'hex'); can be overridden in hash method;

**Comment by maxkfranz** [comment]
Since the option is important, I'd be inclined to make the option explicit in the constructor in case we upgrade the package in future and they change the defaults.  (Some package authors consider an undefined option to mean "I don't care about this option" versus "I'm OK with this specific default value".)

It's not strictly necessary though.

**Comment by jvwong** [comment]
Will declare in options explicitly.
