### ISSUE TITLE
view/components/sidebar/menus/components/downloadOptions

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#167]
https://github.com/PathwayCommons/app-ui/blob/master/src/client/features/view/components/sidebar/menus/components/downloadOption.js#L30

Why can't this be refactored into a if else statement?

Also can't you just not use a tags if you don't want the links to work?

**Comment by maxkfranz** [comment]
Controller functions should have nothing to do with the DOM.  They shouldn't be named things, like `handleClick`.  Name the function by what the function *does*, not what calls the function.

**Comment by maxkfranz** [comment]
https://github.com/PathwayCommons/app-ui/blob/master/src/client/features/view/components/sidebar/menus/components/downloadOption.js#L30

This line shouldn't exist at all.

**Comment by jonahdlin** [comment]
Sorry, to be clear, I want the links to open in a new page when clicked and **not** download the file. Clicking anywhere else on the card will trigger the download, but I thought it would be frustrating to a user who just wants to click a hyperlink if a file downloaded unexpectedly. @maxkfranz where should I do that check?

As for the if else statement I can change it to that instead of just returning.
