### ISSUE TITLE
Some queries can break search

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#191]
APC/C:Cdc20 mediated degradation of Cyclin B

This is a label that came from the Enrichment Map.

**Comment by d2fong** [comment]
Here is the actual pathway when if I go to the reactome id directly:

http://beta.pathwaycommons.org/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-174048

**Comment by d2fong** [comment]
Check the processed queries after escaping lucene here: 

https://github.com/PathwayCommons/app-ui/blob/master/src/client/services/pathway-commons/search/index.js#L19

Possible bug with the string not being escaped.

**Comment by d2fong** [comment]
https://github.com/PathwayCommons/app-ui/blob/master/src/client/services/pathway-commons/search/index.js#L60

Should also check response code here.

**Comment by d2fong** [comment]
Check for irregular characters such as \ or : here
https://github.com/PathwayCommons/app-ui/blob/master/src/client/services/pathway-commons/search/index.js#L37

Generate queries based on if the characters \ or : or anything else that is irregular appears in there.

**Comment by d2fong** [comment]
cpath2 client needs to be changed to return the status. It doesn't do this right now.

https://github.com/PathwayCommons/cpath2-client/blob/master/src/private/pc-request.js#L88

I guess I can just check for null, but I think it is important that the request status is available.

**Comment by d2fong** [comment]
@IgorRodchenkov 
I created a temporary fix for the search.  Here is the first processed query that fails for the above query:

(name:APC/C:Cdc20\ mediated\ degradation\ of\ Cyclin\ B) OR (name:*APC/C:Cdc20\ mediated\ degradation\ of\ Cyclin\ B*) OR (name:*APC\/C\:Cdc20* AND name:*mediated* AND name:*degradation* AND name:*of* AND name:*Cyclin* AND name:*B*)

To check if the query has lucene symbols should I just see if the string has matches for this:
https://github.com/PathwayCommons/app-ui/blob/master/src/client/services/pathway-commons/search/index.js#L24  regex?

The second query sent succeeds:
(name:*APC\/C\:Cdc20* OR name:*mediated* OR name:*degradation* OR name:*of* OR name:*Cyclin* OR name:*B*)

**Comment by IgorRodchenkov** [comment]
Hi Dylan,

The first query that failed, In fact, is different; that is, the line 37 -

'(name:' + removeSpaces(queryString) + ') OR (' + 'name:*' +
removeSpaces(queryString) + '*) OR (' + processedTokens.join(' AND ') + ')'

results in query string -

(name:APC/C:Cdc20\ mediated\ degradation\ of\ Cyclin\ B) OR
(name:*APC/C:Cdc20\ mediated\ degradation\ of\ Cyclin\ B*) OR
(name:APC\/C\:Cdc20 AND name:mediated AND name:degradation AND name:of AND
name:Cyclin AND name:B)

- see there are '*' in the second sub-query, and the third, last sub-query,
uses escaped tokens, i.e., APC\/C\:Cdc20

Anyway, to fix that query, which is important and specific, rather than
ignoring it fails, I would:

   - rename misleading *removeSpaces
   <https://github.com/PathwayCommons/app-ui/blob/master/src/client/services/pathway-commons/search/index.js#L5>*
   method (it does not remove them but escapes with '\') to *escapeLuceneSyntax
   *(or *sanitize)* and use regex:
*token.replace(/([\!\*\+\-\&\|\(\)\[\]\{\}\^\~\?\:\/\\"\\s])/g,
   '\\$1');*
   - at L24
   <https://github.com/PathwayCommons/app-ui/blob/master/src/client/services/pathway-commons/search/index.js#L24>
   simply call the function: *const luceneToken =
   escapeLuceneSyntax(token);*
   - *and, at L37
   <https://github.com/PathwayCommons/app-ui/blob/master/src/client/services/pathway-commons/search/index.js#L37>,
   also call that new function **escapeLuceneSyntax(queryString) in the two
   first sub-queries;*

*(I can do this if you don't mind.)*
*Igor.*

**Comment by d2fong** [comment]
Ok you can do it. We have a code freeze on master so you should change it on the development branch

**Comment by IgorRodchenkov** [comment]
Hi @d2fong, 
ok, I pushed to the development.
