### ISSUE TITLE
Floating (disconnected) nodes

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#228]
There are floating dangling entity and interaction nodes.

**Comment by d2fong** [comment]
@IgorRodchenkov http://beta.pathwaycommons.org/view?uri=http%3A%2F%2Fidentifiers.org%2Fpanther.pathway%2FP04397

**Comment by d2fong** [comment]
Here is another one
/view?uri=http%3A%2F%2Fidentifiers.org%2Fpanther.pathway%2FP00059

**Comment by IgorRodchenkov** [comment]
The TSC2(ct:Dna) node, unlike e.g., TSC2(ct:RNA), is in fact not connected with any arc to anything in the corresponding [SBGN query result](http://www.pathwaycommons.org/pc2/get?uri=http://identifiers.org/panther.pathway/P04397&format=sbgn).
(In the other query/view example, there are several dangling entity and interaction type nodes, also has to do with dna template reactions...)

In the corresponding BioPAX model, the TSC2(DnaRegion) is participant in the same _TemplateReaction_ producing TSC2(ct:RNA). I noticed that the BioPAX model for that DNA transcription process does not look good: instead of having TSC2 DNA as (BioPAX property value) '`template`', there was used parent property '_participant_'; and TSC2 RNA is both '_product_' (correct) and '_participant_' (may be ok but totally unnecessary). I suspect such model causes Paxtools sbgn-converter fails generate correct SBGN model.

We could (probably have to) fix this data issue in three places: 1) in Paxtools' sbgn-converter (a quick dirty fix); 2) suggest Panther Pathway team fix data and make a new release; 3) in the PantherCleaner (component of cPath2 project, Pathway Commons data import).

@d2fong @gbader

**Comment by IgorRodchenkov** [comment]
Fixed in the java sbgn-converter (see 1. above); see 

- http://www.pathwaycommons.org/pathways/#/view?uri=http%3A%2F%2Fidentifiers.org%2Fpanther.pathway%2FP04397
- http://www.pathwaycommons.org/pathways/#/view?uri=http%3A%2F%2Fidentifiers.org%2Fpanther.pathway%2FP00059
- 

Cannot see it at beta.pathwaycommons.org yet, probably, due to caching (could someone purge the cache)... 
@d2fong

**Comment by IgorRodchenkov** [comment]
Another example - dangling _Complex_ type nodes:
`http://beta.pathwaycommons.org/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-6804757`

**Comment by IgorRodchenkov** [comment]
There are still disconnected interaction and complex type nodes (in the second and last exmples)

**Comment by IgorRodchenkov** [comment]
It's fixed now for dangling physical entities and generic complexes. See BioPAX/Paxtools#37
