### ISSUE TITLE
Potentially better way to share common code among a component tree

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#254]
To use common code you require it via directory.
If there is a deeply nested component tree and a child with a large depth wants to access common code, it has to require it via path:
require('../../../../)

Perhaps there is a way that react can make common code available to the whole component without requires.

**Comment by jonahdlin** [comment]
There's a [gist](https://gist.github.com/branneman/8048520) article with 8 ways to do this. The best seems to be number 2, which is

> 1. In your app.js:
> ```js
> global.__base = __dirname + '/';
> ```
> 2. In your very/far/away/module.js:
> ```js
> var Article = require(__base + 'app/models/article');
> ```
We could make different references for different folders, like `global.__client`, `global.__server`, or more specific. It somewhat reverses the problem, since instead of doing `require('../../../ etc ')`, you're now referencing every file from a relative root, `require(__base+'src/client/features/ etc ')`, but at least the paths are descriptive.

**Comment by d2fong** [comment]
Not that relevant now that the directory structure is pretty flat right now.
