### ISSUE TITLE
node tooltip bug

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#282]
http://localhost:3000/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-6803211

- click tp63 macromolecule
- console says cannot get ids publications.js line 60

**Comment by hmtinc** [comment]
@d2fong  I don't get the error on my copy of the application, but it seems the issue is due to a failed query to PUBMED for the publication info. I'll include a fall back just incase pubmed queries fail. 

![screen shot 2017-12-04 at 3 26 18 pm](https://user-images.githubusercontent.com/1313810/33574660-df22192a-d907-11e7-885b-c7e9135e2bc3.png)
