### ISSUE TITLE
Revision history snapshots look 'different'

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#318]
The snapshot looks different than the actual layout on demo branch

See below for 'Transcriptional activation of cell cycle inhibitor p21 | Reactome'

![screenshot at dec 09 11-57-04](https://user-images.githubusercontent.com/4706307/33797682-6a3ae426-dcda-11e7-8abe-bae4c93c4f0e.png)

**Comment by hmtinc** [comment]
@jvwong  It seems to have been a spacing issues caused by parent nodes being assigned a position. I have resolved the issue and issued the pr #325 to pull the changes into the DEMO branch. 

![screen shot 2017-12-11 at 9 25 41 am](https://user-images.githubusercontent.com/1313810/33836035-4a2fec4e-de56-11e7-8fd3-768e946e58a9.png)
