### ISSUE TITLE
Tooltip text is small

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#319]
I am using a macbook air, chrome and the tooltip font size is very small, almost unreadable.

see below example for 'Transcriptional activation of cell cycle inhibitor p21 | Reactome'
![screenshot at dec 09 12-14-42](https://user-images.githubusercontent.com/4706307/33797704-b18974fa-dcda-11e7-8363-b9a6271c6ce9.png)

**Comment by hmtinc** [comment]
The tooltip size was variable based on screen size, the idea was that on higher resolution screens (i.e 4k screens)  the font size would scale to be a lot more readable.  For now, I've changed the font size to a fixed value so that on lower resolution screens/regular 1080p the font is more readable. 

#### 1440 x 900 (Macbook Air) 
![screen shot 2017-12-11 at 8 33 54 am](https://user-images.githubusercontent.com/1313810/33834257-61f4b3d8-de50-11e7-90c1-6bec6571fcbf.png)

#### 1920 x 1080 
![screen shot 2017-12-11 at 8 33 43 am](https://user-images.githubusercontent.com/1313810/33834281-6eb5637e-de50-11e7-99e3-2546535f3f4b.png)

note : This only helps deal with resolution issues and doesn't take into account actual physical screen size. It would be up to the user to run OS or Browser level scaling in the case where their screen resolution is high but their physical screen is fairly small.

**Comment by jvwong** [comment]
Not sure if this is related but now all of the node units of information (little oval with text) are appearing and disappearing (see http://localhost:3000/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-69895 - p53 nodes)

![screenshot at dec 11 12-12-29](https://user-images.githubusercontent.com/4706307/33843873-9ab100a2-de6c-11e7-9188-c7193189041b.png)

**Comment by hmtinc** [comment]
@jvwong The nodes unit of information seem to be appearing properly on our local copy of the demo branch. It may be an issue with your current build, maybe try reseting your branch with the remote demo branch.

**Comment by jvwong** [comment]
Same issue on dc2c6b6465d4e1704f43fa1e0ed04a5c00cfaa98 demo.

I noticed this behaviour when mousing over and out of nodes - this makes the units disappear.

**Comment by d2fong** [comment]
Does it still happen if you checkout this commit: 520c60831ba12cf91c7cfdad75ae59b98d63bf5b

remove node modules, reinstall npm, restart rethinkdb

**Comment by jvwong** [comment]
The commit you mentioned above works fine.

**Comment by d2fong** [comment]
can you try this commit?  just delete node modules this time, it is possible that it is from the unstable version of cytoscape

5c88d99393a5dc3fc1d3709f37a7230a5d1bcc11

**Comment by d2fong** [comment]
If it still works fine for 5c88d99393a5dc3fc1d3709f37a7230a5d1bcc11, then it is probably a bug introduced by a commit in the last six days.  

869593c8e6973ca7925e03a38e88f2921b564d9e this commit is also suspect, it uses the updated sbgn stylesheet build -- no code changes just uses new tooling (webpack, etc).

**Comment by d2fong** [comment]
You might also want to see if the latest commit on the demo branch works.  You might just have had to reinstall your node modules.

**Comment by jvwong** [comment]
Now (d02661e1e507a55a38fe72579cd5c24fe7686240) it appears all units of information are gone altogether (on that pathway)?

**Comment by hmtinc** [comment]
The small font size issue has been resolved. @d2fong has created a separate issue for the lack of unit information #333.

**Comment by maxkfranz** [comment]
Usually you specify your root font size in [points](https://en.wikipedia.org/wiki/Point_(typography)).  Then you specify font sizes of specific selectors with relative units, like `em` or `rem`.

Points are independent of pixel density -- they indicate physical size.
