### ISSUE TITLE
Add expand/collapse option in the tooltip

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#321]

**Comment by hmtinc** [comment]
@d2fong Given that the tooltip is meant for information, it feels that adding a expand/collapse button would over-complicate the tooltip. How about adding a context menu in addition to the tooltip?

![screen shot 2017-12-11 at 9 37 53 am](https://user-images.githubusercontent.com/1313810/33836551-b1d62ea2-de57-11e7-9ef8-95f1a43b5a37.png)

**Comment by jvwong** [comment]
I vote yes on the context-menu. I think there are additional functionalities that would be put here in the future so good to have it ready. For example, edit this pathway via [Newt](https://github.com/iVis-at-Bilkent/newt/issues/187), search other pathways with this gene (Igor has this info ready)

**Comment by gbader** [comment]
The problem with right click is that it's not easily visible and as a result I don't think many people will find and use it. Right click is good for power user apps that have a lot of functionality.  Our apps are much simpler and if we get to the high number of features that need a right click menu, then I would question whether we need all of those features for an app.  It's also not good to make things more complex for potential future features - best to only do that once we need those features, otherwise it's over-engineering (bad).  GeneMANIA handles this by adding a couple of buttons on the tooltip (e.g. for adding a node to a query), but even then, I doubt people are using this functionality. But even then I doubt people use this because it's easier to just issue a new query.

**Comment by jvwong** [comment]
I would be fine with disabling this in the UI (but keeping it in the code).
