### ISSUE TITLE
Paint - biopax to sbgn mapping issues

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#326]
https://github.com/PathwayCommons/app-ui/issues/320

**Comment by d2fong** [comment]
https://github.com/PathwayCommons/app-ui/issues/223

**Comment by IgorRodchenkov** [comment]
Yes, the SBGN representation does not contain all IDs that can be seen (extracted from) in the corresponding BioPAX, SIF, GSEA (.gmt). This is mainly because there are secondary `xref`, `memberEntityReference`, `memberPhysicalEntity` values, and there is no place in SBGN model to keep them (but if there is such feature or hack in SBGN-ML, we'd update our BioPAX to SBGN converter to support more IDs per node).

However, one still could find all gene/protein/chemical IDs using entity URI and PC's `/traverse?path=...&uri=...` queries.

I think, we could even modify existing PC's `/get` web service so that `/get?uri=..&format=gsea` would return the list of IDs not only for sub-networks (pathways and interactions) but also for physical entities or genes (or entity references) as well...
What do you think, @d2fong @jvwong @gbader ?

**Comment by d2fong** [comment]
So is it possible to make gmt files that match the contents of sbgn more accurately?

**Comment by IgorRodchenkov** [comment]
No, the other way around (if possible ) - the idea is to query PC ws for more IDs for a node...

**Comment by d2fong** [comment]
We already do that.  Harsh combined the metadata for each node. 

@jvwong Since each each gene has a bunch of synonym names in the metadata maybe we could update the way node labels are displayed.

Instead of just getting the label from the sbgn, we could get the label from the metadata and check each gene synonym for each expression.  Then if the label is a match for a specific synonym, set that synonym to be the label on the node.

**Comment by IgorRodchenkov** [comment]
Great.. But if what you do (combine, metadata) is correct, then an sbgn model (or corresponding Cytoscape js model) must contain all the IDs that  the corresponding GSEA result contains; otherwise your metadata is incomplete...

 Let’s talk on Thursday (I feel some misunderstanding here; perhaps we’re talking about different things...)

**Comment by jvwong** [comment]
There are some small details here that @IgorRodchenkov can correct me if I am off:

- Harsh's tooltip code does indeed grab all synonyms for an entity
- The SBGN - GMT mismatches can arise from an issue other than synonyms:
    - For instance, consider our Panther [ras pathway](http://beta.pathwaycommons.org/view?uri=http%3A%2F%2Fidentifiers.org%2Fpanther.pathway%2FP04393). In biology, the  'JNK' node doesn't refer to an actual gene, but rather this is a generic name  could be one of  'MAPK8', 'MAPK9' or 'MAPK10'. In BioPAX, this concept is implemented as a 'hack' in the form of the dreaded 'bp:memberPhysicalEntity'. Aside: This is also why, in the search, the numParticipants may not match the SBGN-ML nodes number. Basically, *three possible* genes are subsumed into this generic container called 'JNK'. GMT files report all three genes whereas SBGN only reports 'JNK' as the label, which I think is the correct behaviour.

Solutions:
  - Using the webservice to lookup each SBGN node is fine in the case of a small pathways, but do we really want the Painter making 200 simultaneous Ajax calls and parsing the result for a pathway of size 200?
  -   Trying to shove the entities into SBGN-ML is ok I guess, but is sort of a fit-for-purpose solution aka 'hack'.

**Comment by IgorRodchenkov** [comment]
In BioPAX,  there are memberPhysicalEntity (not recommended) and memberEntityReference properties which are quite different but confusing all the same...

As to SBGN and out Painter app, as I said, let’s talk... because it seems you lost me - I am not sure what’s the issue and what we want here anymore...

**Comment by IgorRodchenkov** [comment]
How about something like PathwayCommons/cpath2#290 ?

**Comment by IgorRodchenkov** [comment]
So, Paxtools can generate JSON output is like this:

```
[
...
{"UniProt":["P45983","P53779","P45984"],"organism":["Homo sapiens"],"datasource":["PANTHER"],"name":["JNK"],"label":"JNK","HGNC Symbol":["MAPK10","MAPK9","MAPK8"],"type":"Protein","uri":"http:\/\/pathwaycommons.org\/pc2\/Protein_9dd2642b7d83542c25f3a609b0c56a0f","generic":true},
...
]
```

I will upload 'physical_entities.json.gz' to the latest release [PC downloads](http://www.pathwaycommons.org/archives/PC2/v9/).

**Comment by IgorRodchenkov** [comment]
@d2fong, @jvwong 
I generated and uploaded the physical_entities.json.gz to the current release folder in [PC archives](http://www.pathwaycommons.org/archives/PC2/v9/).

**Comment by d2fong** [comment]
Okay great.  Thanks Igor.
