### ISSUE TITLE
Search result -- nothing displayed. TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by ariutta** [PathwayCommons/app-ui#369]
Hello,

I tried searching for tp53, but there was an error that meant the display was blank.

URL: http://beta.pathwaycommons.org/search?gt=0&lt=250&q=tp53&type=Pathway
Browser: Chrome Version 63.0.3239.84
OS: macOS Sierra

Error:
> deps.js:36 TypeError: Cannot read property 'name' of undefined
    at bundle.js:1
    at Array.map (<anonymous>)
    at t.value (bundle.js:1)
    at s (deps.js:36)
    at beginWork (deps.js:36)
    at i (deps.js:36)
    at a (deps.js:36)
    at u (deps.js:36)
    at x (deps.js:36)
    at w (deps.js:36)
s @ deps.js:36
bundle.js:1 Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at bundle.js:1
    at Array.map (<anonymous>)
    at t.value (bundle.js:1)
    at s (deps.js:36)
    at beginWork (deps.js:36)
    at i (deps.js:36)
    at a (deps.js:36)
    at u (deps.js:36)
    at x (deps.js:36)
    at w (deps.js:36)

**Comment by jvwong** [comment]
I traced this to undefined variable `dsInfo` in [app-ui/src/client/features/search/index.js](https://github.com/PathwayCommons/app-ui/blob/3d1e1bdac4dfd0d7ce60067f85306ff4a4ae7ddd/src/client/features/search/index.js#L106-L120) 
```js
  const searchResults = state.searchResults.map(result => {
      const dsInfo = _.find(state.dataSources, ds => {
        return ds.uri === result.dataSource[0];
      });

      return h('div.search-item', [
        h('div.search-item-content', [
          h(Link, { to: { pathname: '/view', search: queryString.stringify({ uri: result.uri }) }, target: '_blank' }, [
            h('h3.search-item-content-title', result.name || 'N/A'),
          ]),
          h('p.search-item-content-datasource', ` ${dsInfo.name}`),
          h('p.search-item-content-participants', `${result.numParticipants} Participants`)
        ])
      ]);
    });

```

whose value is set with call to /pc2/datasources in [`/client/services/apiCaller/index.js`](https://github.com/PathwayCommons/app-ui/blob/3d1e1bdac4dfd0d7ce60067f85306ff4a4ae7ddd/src/client/services/apiCaller/index.js#L25) but I suspect the latter response is coming in later than former? Hard to reproduce error because of caching datasources call?

![image](https://user-images.githubusercontent.com/4706307/34651826-c4764996-f3a3-11e7-8a2e-b5af7c3a57ed.png)

**Comment by IgorRodchenkov** [comment]
Confirmed - 
http://apps.pathwaycommons.org/search?gt=0&lt=250&q=tp53&type=Pathway
- works.
