### ISSUE TITLE
Pathway view - search input text clear button ambiguous

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#370]
The clear text icon has been confused with toggle search.

**Comment by jvwong** [comment]
Hide clear icon if no input text

**Comment by d2fong** [comment]
@wxli0 I am going to assign this ticket to you.  You will have to change the search bar in the view again.

Change it so that there is no 'x' in the search box when there is no input:
![screen shot 2018-01-11 at 12 46 39 pm](https://user-images.githubusercontent.com/2328291/34838821-80223aa2-f6cd-11e7-85c8-d1c983602b30.png)


If there is input, then make the x appear

**Comment by jvwong** [comment]
@wxli0 I am not sure this is addressed by pull request https://github.com/PathwayCommons/app-ui/pull/391
