### ISSUE TITLE
Search - Add datasource branding

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#371]

**Comment by jvwong** [comment]
![screenshot at jan 04 15-11-26](https://user-images.githubusercontent.com/4706307/34582350-8bfd40ae-f161-11e7-92a5-87d0b5ac90b1.png)

**Comment by logmosier** [comment]
So you want the datasource logos to appear next to their names in the search results?

**Comment by jvwong** [comment]
Yes. This is a good time to practice doing a simple mock-up, post here, then get feedback.

**Comment by logmosier** [comment]
Any feedback?
![screen shot 2018-01-15 at 3 31 58 pm](https://user-images.githubusercontent.com/10948303/34960681-de24e962-fa09-11e7-8b4b-db4b826b2d2c.png)
![screen shot 2018-01-15 at 3 32 26 pm](https://user-images.githubusercontent.com/10948303/34960686-e077fc18-fa09-11e7-9a80-3cc1c58e251b.png)

**Comment by d2fong** [comment]
This is a good start and this is the design that we used to have, but I think what Jeff was asking of you was to create a few different mockups (probably by pencil and paper) so that we could explore different possibilities/designs for this page.

The main feedback we got from this is page is that there is redundant information (the data source name and the branding) both provide mostly the same thing but the branding does it in a way that is easier for humans to recognize
