### ISSUE TITLE
Landing Page Mockup

### ISSUE THREAD

**Issue by logmosier** [PathwayCommons/app-ui#395]
Initial mockup for the landing page, thoughts?
![screen shot 2018-01-22 at 12 21 04 pm](https://user-images.githubusercontent.com/10948303/35234324-c36af002-ff6e-11e7-8ba5-3af8cea6e825.png)

**Comment by logmosier** [comment]
![screen shot 2018-01-22 at 2 20 00 pm](https://user-images.githubusercontent.com/10948303/35239839-9694e0e0-ff7f-11e7-8b4e-3d6d3f89fe23.png)

**Comment by jvwong** [comment]
- We might want to provide helpful text descriptions of gene functions for users similar to [signor](http://signor.uniroma2.it/relation_result.php?id=Q13315). This might also help the page to get indexed by search engines for queries related to the gene.    

![image](https://user-images.githubusercontent.com/4706307/35240384-414147bc-ff81-11e7-8433-fe3c888e5aba.png)

- minor: Remove the list element dots

**Comment by logmosier** [comment]
![screen shot 2018-01-22 at 3 09 35 pm](https://user-images.githubusercontent.com/10948303/35242454-9b12dd2c-ff87-11e7-85e0-789bf315e0e7.png)

**Comment by jvwong** [comment]
Just noting that Pathway Commons only stores human pathways and interactions. UniProt however covers many species.

**Comment by maxkfranz** [comment]
Some notes

- Could use spacing instead of titles.
  - Synonyms can just go under the name.  Proximity to the name (title) shows that these are synonyms.
  - Links can just go at the very bottom with some space above.  You're probably not interested in links until after you've skimmed the rest.  A user probably wants to have an idea of what they're looking at before clicking out to another site to get even more information.
  - "Functions" is like a description, so it's also probably fine without a title as long as you use a little spacing.
- Species probably doesn't need its own line.  It could be combined on the title line.
- The logo is huge, in my opinion.  It's probably fine as a small favicon-like image at the bottom with the source name, like how DuckDuckGo does it:

<img width="1144" alt="screen shot 2018-01-22 at 4 30 44 pm" src="https://user-images.githubusercontent.com/989043/35245518-a38f1f06-ff91-11e7-81a1-d2d513c9dc58.png">

**Comment by logmosier** [comment]
Where you thinking something like this Max?
![screen shot 2018-01-23 at 1 40 29 pm](https://user-images.githubusercontent.com/10948303/35293884-1ab84984-0043-11e8-9909-39891d56c482.png)
Also do we have the favicons for the sites?

**Comment by d2fong** [comment]
@gbader @IgorRodchenkov Logan is working on the mockup for the protein landing page here.  Do you have any comments to add on the mockup?

**Comment by maxkfranz** [comment]
@logmosier Yes, I was thinking of something like that.  It looks much better to me.

I'm not crazy about the big logos, though.  You can grab the favicons from the sources themselves.  If you go to Reactome, for example, you can see the favicon in the source: 

<img width="1228" alt="screen shot 2018-01-24 at 12 57 19 pm" src="https://user-images.githubusercontent.com/989043/35348486-3423e9e6-0106-11e8-803a-9363e785bca4.png">

Favicons like these are designed to be scaled down, and they're easier to fit in the UI because they're square rather than random rectangles.

**Comment by jvwong** [comment]
- Referrer datasource logo/branding/name should be integrated, preferably inline
- Put species and gene name inline

**Comment by IgorRodchenkov** [comment]
@logmosier @d2fong @jvwong 
I can see in PC2 service logs someone sends a query with a typo in it, which results in error -  please note that in the query `"/pc2/search?q=ATM&type=ProtineReference"` it should be Prot**ein**Reference (check spelling elsewhere, because I have noticed such errors many times already ;)))
