### ISSUE TITLE
Expose selected parameters for enrichment service

### ISSUE THREAD

**Issue by wxli0** [PathwayCommons/app-ui#533]
expose
- orderedQuery
- userThr
- minSetSize
- maxSetSize
- threadholdAlgo
- custbg
- custbgCb
on branch enrichment-expose, referring to #481 comments

**Comment by jvwong** [comment]
An excerpt form BIIT support about the data sources. Probably a separate issue? If there is overlap with [Pathway Commons datasources](http://www.pathwaycommons.org/pc2/datasources) (exclude sf_MI, sf_HPA, sf_HP) then we should consider including them. The idea being: What if we swapped out our own enrichment implementation using our own data, then it would be invisible to clients because we are supporting the same data sources.

> In the HTTP POST you can indeed specify only the data sources which you want to keep
>
> The parameters include:
sf_GO  - includes BP, CC, MF subcategories of GO
sf_GO:BP - includes GO biological process terms (if used together with sf_GO then the intersection is applied i.e. sf_GO:BP and sf_GO will give only sf_GO:BP terms)
sf_GO:CC - includes GO cellular component terms
sf_GO:MF - includes GO molecular function terms
sf_KEGG - includes KEGG pathways
sf_REAC - includes Reactome pathways
sf_TF - includes transcription factor predictions from Transfac
sf_MI - includes miRBase predictions
sf_HPA - includes Human Protein Atlas data
sf_CORUM - includes CORUM protein complexes
sf_HP - includes Human Phenotype Ontology terms
sf_BIOGRID - includes Biogrid protein complexes

**Comment by jvwong** [comment]
FYI: [g:Convert option 'underrep'](https://biit.cs.ut.ee/gprofiler/help.cgi?help_id=61)

![image](https://user-images.githubusercontent.com/4706307/37604458-67cb2eae-2b67-11e8-9b6c-90b94ca0b6be.png)

This should default to 0/false and never be exposed.

**Comment by jvwong** [comment]
With regards to parameters `significant`, `threshold`, and `user_thr` there is a relationship between them in g:GOSt that is not easy to discern from their web page. Here's my interpretation.



- `threshold_algo`
  - One of  "analytical", "bonferroni", "fdr"
  - When "fdr" is selected, it [sets the significant threshold to 0.05] (https://biit.cs.ut.ee/gprofiler/help.cgi?help_id=7).    

- `user_thr`
  - Real number in [0, 1].  
    - Recall that the `threshold_algo` already has a significance threshold (i.e. < 0.05 for "fdr") built-in. If you want to see results with significance value larger than this (i.e. (0.05, 1]) then you set this number.   

- `significant`
  - boolean. 
    - 1 means only return results declared as significant (`"signif": "!"`), that is, results below the significance threshold. What is the significance threshold? Well that depends on what you for `threshold_algo` (i.e. for "fdr" this is <0.05).
    - 0 means return everything. However, keep in mind that the `"signif": "!"` field always refers to the signficance threshold set by `threshold_algo` and NOT by the `user_thr`. This is confusing.

**Comment by jvwong** [comment]
So the take home message is:

`significant` means return results below '0.05'
`user_thr` means return everything below this value, but ONLY if `significant = false`

**Comment by wxli0** [comment]
I understand the relationship between significance, threshold_algo and user_thr, but am confused about what I should do with my service. Should I expose them and process the output to illustrate the above logic (adding significance_level_for_exclamation, and significance_level_for_displaying fields)?

**Comment by jvwong** [comment]
What about this (correct me if I am wrong, unclear):

Set `significant = 0`. Always. Do not expose it at all.
Set `user_thr = 0.05` by default
Set `threshold_algo = fdr` by default 
Ignore 'signf' field - that is, do not return in any output.

**Comment by wxli0** [comment]
Since 'signf' field is ignored, does it matter what threshold_algo we choose?

**Comment by wxli0** [comment]
Why does GOst still return the so many results when setting user_thr to -20? Shouldn't it return rows with p-value < -20 which is impossible?
![screen shot 2018-03-19 at 3 37 46 pm](https://user-images.githubusercontent.com/24982880/37618320-4b4702b0-2b8c-11e8-9491-3ace1c2784d7.png)

**Comment by jvwong** [comment]
p is a real number on [0, 1].

**Comment by wxli0** [comment]
[gprofiler help](https://biit.cs.ut.ee/gprofiler/help.cgi#help_id_8) doesn't specify what if user enters an out of range value for user_thr. I think it uses the default one (user_thr=1) when invalid. Should we report an error if user_thr is out of range?

**Comment by jvwong** [comment]
Yes that makes sense.

**Comment by wxli0** [comment]
moved to #541
