### ISSUE TITLE
Updating Swagger/Documentation 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#732]
- [ ] Remove the 'Authorize' button
- [ ] Complete ‘Models’ section
- [ ] Review Model inputs to include useful descriptions and clarify what each represents

**Comment by jvwong** [comment]
OK cool. Let's beef up the descriptive content.

**Comment by CaitlinOCallaghan** [comment]
Ok! Sounds good, I will work on altering the content. Also, each model can be found under the drop down for the specific service, but there is also a models section at the bottom of the page that is currently empty. In swagger doc examples, the models in the drop downs are the same as those in the bottom section. Since it's just a duplicate, should we remove the models section at the bottom? 

The drop down models contain content:
![image](https://user-images.githubusercontent.com/38890251/40255236-6e41eaee-5ab4-11e8-842b-171a9aee8977.png)

But the models section itself is empty:
![image](https://user-images.githubusercontent.com/38890251/40255248-8012408e-5ab4-11e8-8727-72805de44ad6.png)

**Comment by jvwong** [comment]
Yes just remove those at the bottom if they are not informative.

**Comment by jvwong** [comment]
What's with the error (bottom right)?
```text
https://online.swagger.io/validator/debug?url=/api/swagger.json
```

**Comment by CaitlinOCallaghan** [comment]
This statement describing the visualization service is vague ( line 32, enrichment-rest.js) : "Arbitrary key-value pairs under a pathway ID are passed-through to nodes" .  Do you have suggestions on how to clarify what it is referencing, or would it be best to delete it? 

Also, I'm looking into the error notification now.

**Comment by jvwong** [comment]
> This statement describing the visualization service is vague ( line 32, enrichment-rest.js) : "Arbitrary key-value pairs under a pathway ID are passed-through to nodes" . Do you have suggestions on how to clarify what it is referencing, or would it be best to delete it?

For `visualization`, you can POST something like the following: 

```js
{
	"pathwayInfoList": {
		"GO:0006354": {// arbitrary data			
	                "p-value": 0.0265,
			"description": "DNA-templated transcription, elongation",
		},
		...
	}	
}
```

The  object containing arbitrary data is passed verbatim into the data node in the output JSON.

```js
{
	"unrecognized": [],
	"graph": {
		"elements": {
			"nodes": [
				{
					"data": {
						"id": "GO:0006354",
						"p-value": 0.0265,
						"description": "DNA-templated transcription, elongation",
						...
						]
					}
				},
				...
			],
			"edges": [
				...
			]
		}
	}
}
```

> Also, I'm looking into the error notification now. 
  
see https://github.com/Surnet/swagger-jsdoc/issues/80

**Comment by jvwong** [comment]
Sure looks good to go - do the pull request. Combine any subsequent text updates with actual code/parameter changes.
