### ISSUE TITLE
Remove extra steps to Datasource   

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/app-ui#761]
## Description of new feature

Related to #687 

We have a 'Datasource' toggle that shows a dropdown labelled with the current datasource. The user needs to look across the the screen to the datasource label, then select from the dropdown. 

![image](https://user-images.githubusercontent.com/4706307/40060551-e42a5b66-5824-11e8-8d63-3aac926e270c.png)

Question: Is there a simpler way to offer this?

## Motivation for new feature

Reduce the amount of work needed by a user to filter.

**Comment by jvwong** [comment]
Maybe ditch the 'Datasource' toggle in your second image?

**Comment by CaitlinOCallaghan** [comment]
So remove the 'Datasource' header and have the filter drop down appear upon loading?

**Comment by jvwong** [comment]
Yes. Simple dropdown to select datasource.

**Comment by CaitlinOCallaghan** [comment]
Here is what it looks like on full screen:
![image](https://user-images.githubusercontent.com/38890251/40073590-3edc3e7e-5845-11e8-977e-544bdcb7797c.png)

If you decrease screen width, the filter menu slides with the rest of the search page so that it is always at the edge of the description box. It also fits on phone views. My only concern is that when you open the menu on the phone, the display is:
![image](https://user-images.githubusercontent.com/38890251/40073774-d171ee00-5845-11e8-93bc-913ec38da42c.png)

Does this mean the filter menu will be slightly cut off when opened on phone?

**Comment by jvwong** [comment]
I think these things always depends on the phone/browser. I could live without filtering on small devices. What do you think?

**Comment by CaitlinOCallaghan** [comment]
I agree, because the filter bar does show up on the screen; however, it's when you open it that a portion may be cut off on smaller phones. 

![image](https://user-images.githubusercontent.com/38890251/40074625-16129634-5848-11e8-88fa-1194837fb772.png)

**Comment by CaitlinOCallaghan** [comment]
Are there any more changes that I should make, or can I submit a pull request?

**Comment by jvwong** [comment]
Let's go with this.

**Comment by maxkfranz** [comment]
The dropdown only looks like that in the Chrome debug mode in the browser.  It doesn't get all of the details right when it's in the "mobile phone simulator" mode.  If you use an iPhone, you'll get the rolodex UI for the select box.

**Comment by IgorRodchenkov** [comment]
@jvwong  @CaitlinOCallaghan 

First, the _datasources_ filter (../pc2/search) accept an array of values; so - should be multiple choice list or drop-down menu. Also, let's not use the parameter when then no values are selected (instead of sending tailing '&' as it seems to be now).

Second, no all the available datasources have in fact Pathways; e.g., _intact, biogrid, phosphositeplus_ dont' have any. So, when (and only) we search for pathways (using _type=pathway_ query parameter), we could use one of the following approach : 

1. exclude interactions-only data sources from the values list in advance; this can be done using `numPathways` filed in the matadata about datasources; see e.g. http://beta.pathwaycommons.org/pc2/metadata/datasources/reactome; we could e.g. add and use a new _hasPathways_ value [here](https://github.com/PathwayCommons/pathway-commons-client/blob/master/src/datasources.js#L37) or - in my refactored app-ui branch - [here](https://github.com/PathwayCommons/app-ui/blob/issue_764_etc/src/server/pathway-commons/index.js#L99). 
2. alternatively, do not use _datasource_ filter at first, - implement optional filtering after getting search hits (unique data source names can be extracted from the search result and used for post-filtering).
