### ISSUE TITLE
Painter is broken

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/app-ui#890]
??

**Comment by jvwong** [comment]
I've noticed a few cases where the app seems to generate "odd" results, which can be confusing to users. It's not necessarily that the app has a bug, although there are some. A few examples below:

## Pathway Data/Pathway Commons 
### How pathways and subpathways are represented in GMT vs SBGN vs BioPAX
  - The BioPAX object itself contains references to subpathway objects (i.e. pathwayComponent/stepProcess). 
  - Gene sets (GMT - like those produced by [baderlab](http://baderlab.org/GeneSets) or those used in [g:Profiler](https://biit.cs.ut.ee/gprofiler/gmt/gprofiler_hsapiens.NAME.gmt.zip))  ‘flatten’ pathway hierarchies by including all entities from subpathways 
  - SBGN only contains entities explicitly declared in the given BioPAX object and contains no reference to subpathways 

Consider the case of the Reactome pathway [Glycerophospholipid biosynthesis](https://reactome.org/PathwayBrowser/#/R-HSA-1483206)
![image](https://user-images.githubusercontent.com/4706307/42838649-5a51e7f6-89cf-11e8-9d5b-0e054ed04b09.png)

The GMT file `baderlab Human_GO_AllPathways_no_GO_iea_July_01_2018_symbol.gmt` says this pathway has 123 elements. The corresponding pathway from the gene set downloaded from g:Profiler on July 5th is 127. PC v10 says this pathway has 5 elements.

### SBGN labels are not HGNC approved symbols
  - Consider ([PD-1 Signaling | Reactome](https://reactome.org/PathwayBrowser/#/R-HSA-389948)), specifically a reaction involving PTPN6, PTPN11: 

![image](https://user-images.githubusercontent.com/4706307/42839418-af4decd0-89d1-11e8-8379-673cdb477db6.png)

The corresponding reaction in PC apps references SHP1, SHP2 which are synonyms for [PTPN6](https://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=9658) and PTPN11.

![image](https://user-images.githubusercontent.com/4706307/42839377-8d11b048-89d1-11e8-961e-397354cbafaa.png)

Nevertheless, the [GMT file from Pathway Commons](http://www.pathwaycommons.org/archives/PC2/v10/PathwayCommons10.reactome.hgnc.gmt.gz) specifically references the HGNC approved symbols (PTPN6, PTPN11) rather than the synonyms.

## Painter App
### The generic label is shown, but not any of the entities making up that generic
- Showing the generic label but not the entities making up that generic leads to confusion because it appears as though some genes in Painter are 'missing'. Not displaying  generic components  makes it tough for the user to align the gene set/heatmap they see in Cytoscape with the Painter panel 

Consider a case ([Signaling by Ras mutants | Reactome](https://reactome.org/PathwayBrowser/#/R-HSA-6802949&SEL=R-HSA-5672717&PATH=R-HSA-1643685,R-HSA-5663202,R-HSA-6802957&DTAB=MT)):

![image](https://user-images.githubusercontent.com/4706307/42839816-d575cf12-89d2-11e8-8d50-cee7227c4789.png)

Notice that the glyph [‘RAF/MAPK scaffolds’](https://reactome.org/PathwayBrowser/#/R-HSA-6802949&SEL=R-HSA-5672717&PATH=R-HSA-1643685,R-HSA-5663202,R-HSA-6802957&DTAB=MT) contains 24/54 of the genes of the pathway! Given our approach, 24 genes in the gene set /heatmap will be collapsed into this single node labelled 'RAF/MAPK scaffolds', nowhere to be accessed by the user:

![image](https://user-images.githubusercontent.com/4706307/42840398-bce76ad0-89d4-11e8-8294-ee4bad9b58ad.png)

> Note: Using /Users/jeffreywong/Sync/bader_jvwong/Apps/Painter/PathwayCommons10.reactome.hgnc.cys 

### The painter search strategy is good, but not perfect 

- the tab for 'select pathway' probably isn't obvious to new users. I found it pretty good, identifies the correct pathway amongst the top returned, but the right one is a 'tie' that isn't selected for display. See the case above.   

### Bugs (see #879)

**Comment by IgorRodchenkov** [comment]
If you'd like, we'd discuss "how pathways and subpathways are represented in GMT vs SBGN vs BioPAX" and I'd probably help you understand some implementation details (PC2 web services) or plan for new features or options (like 'subpw') ...

**Comment by jvwong** [comment]
@IgorRodchenkov yes, let's talk about this. I was thinking about whether a 'mapping file' service was worth the work. Not sure.

**Comment by jvwong** [comment]
Closing metaissue for more specific action items: #953 and will open new one to address subpathways.
